# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flexroster < Formula
  desc "A cli tool to manage your FlexRoster instance"
  homepage "https://github.com/biohackerellie/FlexRoster"
  version "1.10.8"

  on_macos do
    on_intel do
      url "https://github.com/biohackerellie/FlexRoster/releases/download/v1.10.8/FlexRoster_1.10.8_darwin_amd64.tar.gz"
      sha256 "3bc9eab8d64ea825dca901ee1df52cf5a9ccd99ad9f64dccc2800c0511a1af85"

      def install
        bin.install "flexroster"
        etc.install "config.yaml"
      end
    end
    on_arm do
      url "https://github.com/biohackerellie/FlexRoster/releases/download/v1.10.8/FlexRoster_1.10.8_darwin_arm64.tar.gz"
      sha256 "54b82a7e09759bc685b06df797e4cfc00ae036661915273f0b4c635a276e63d6"

      def install
        bin.install "flexroster"
        etc.install "config.yaml"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/biohackerellie/FlexRoster/releases/download/v1.10.8/FlexRoster_1.10.8_linux_amd64.tar.gz"
        sha256 "33d21ffbbb2d4cd6006f21176574417532d312bc5aa242a831043a8915353379"

        def install
          bin.install "flexroster"
          etc.install "config.yaml"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/biohackerellie/FlexRoster/releases/download/v1.10.8/FlexRoster_1.10.8_linux_arm64.tar.gz"
        sha256 "ea468f0e5510a338166bf6a3f2b398d81c06774b71c121b16b65e9183ddf3ebe"

        def install
          bin.install "flexroster"
          etc.install "config.yaml"
        end
      end
    end
  end

  test do
    system "#{bin}/flexroster version"
  end
end
