# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flexroster < Formula
  desc "A cli tool to manage your FlexRoster instance"
  homepage "https://github.com/biohackerellie/FlexRoster"
  version "2.0.6-nightly.20250123"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/biohackerellie/FlexRoster/releases/download/v2.0.6-nightly.20250123/FlexRoster_2.0.6-nightly.20250123_darwin_amd64.tar.gz"
      sha256 "fd45eb1ea327195328911472132e1f56a20c16fe5f85f22981cb4681ce8b6297"

      def install
        bin.install "flexroster"
        etc.install "config.yaml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/biohackerellie/FlexRoster/releases/download/v2.0.6-nightly.20250123/FlexRoster_2.0.6-nightly.20250123_darwin_arm64.tar.gz"
      sha256 "73fabbddcf3b589cdfff7de9bef7d785d5441caa41526a9f5ba02d0249d7c860"

      def install
        bin.install "flexroster"
        etc.install "config.yaml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/biohackerellie/FlexRoster/releases/download/v2.0.6-nightly.20250123/FlexRoster_2.0.6-nightly.20250123_linux_amd64.tar.gz"
        sha256 "2a2b47bdc15a818695c0b7ed212cb77bcfdf2af4e5157cecea14163071781d3c"

        def install
          bin.install "flexroster"
          etc.install "config.yaml"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/biohackerellie/FlexRoster/releases/download/v2.0.6-nightly.20250123/FlexRoster_2.0.6-nightly.20250123_linux_arm64.tar.gz"
        sha256 "7874679ef7fc48894cba13f51cdc46d4daa566fd36050ca494328ea4eacccc8e"

        def install
          bin.install "flexroster"
          etc.install "config.yaml"
        end
      end
    end
  end

  test do
    system "#{bin}/flexroster version"
  end
end
