# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flexroster < Formula
  desc "A cli tool to manage your FlexRoster instance"
  homepage "https://github.com/biohackerellie/FlexRoster"
  version "1.9.2"

  on_macos do
    on_intel do
      url "https://github.com/biohackerellie/FlexRoster/releases/download/v1.9.2/FlexRoster_1.9.2_darwin_amd64.tar.gz"
      sha256 "8b9ae021033851d8d68520c691fc014dd2043ca8d1c55f4ad97c95ec15b82d23"

      def install
        bin.install "flexroster"
      end
    end
    on_arm do
      url "https://github.com/biohackerellie/FlexRoster/releases/download/v1.9.2/FlexRoster_1.9.2_darwin_arm64.tar.gz"
      sha256 "e38682df621c0bf03603279c9980e31d29ffd366ebe565e19eb5cf1668f6c02e"

      def install
        bin.install "flexroster"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/biohackerellie/FlexRoster/releases/download/v1.9.2/FlexRoster_1.9.2_linux_amd64.tar.gz"
        sha256 "06ec7111aea7a9a965888aa059d5b0a6a46d1f2e618574708271102275fc2ac4"

        def install
          bin.install "flexroster"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/biohackerellie/FlexRoster/releases/download/v1.9.2/FlexRoster_1.9.2_linux_arm64.tar.gz"
        sha256 "260e4016669b007e07d07294249c3dd1ce3289ee6d5d36717f27f728b96ac6ee"

        def install
          bin.install "flexroster"
        end
      end
    end
  end
end
