# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flexroster < Formula
  desc "A cli tool to manage your FlexRoster instance"
  homepage "https://github.com/biohackerellie/FlexRoster"
  version "1.9.1-develop.0"

  on_macos do
    on_intel do
      url "https://github.com/biohackerellie/FlexRoster/releases/download/v1.9.1-develop.0/FlexRoster_1.9.1-develop.0_darwin_amd64.tar.gz"
      sha256 "1cbbcb4f2f77857edea396351867be8aa1dcdf58f987b590b63e22ebfb6457f2"

      def install
        bin.install "flexroster"
      end
    end
    on_arm do
      url "https://github.com/biohackerellie/FlexRoster/releases/download/v1.9.1-develop.0/FlexRoster_1.9.1-develop.0_darwin_arm64.tar.gz"
      sha256 "360e1fb8f80a118db5ab02febdb93435c79be488da8dfef8019912f1236a7b73"

      def install
        bin.install "flexroster"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/biohackerellie/FlexRoster/releases/download/v1.9.1-develop.0/FlexRoster_1.9.1-develop.0_linux_amd64.tar.gz"
        sha256 "5247a8c33b927ed71273ab0aef5fddc033489529442497931443aaedca0487d4"

        def install
          bin.install "flexroster"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/biohackerellie/FlexRoster/releases/download/v1.9.1-develop.0/FlexRoster_1.9.1-develop.0_linux_arm64.tar.gz"
        sha256 "4c248761639059219731994eb3b5e93a27d004e1661489d8a211f4330f9e7efa"

        def install
          bin.install "flexroster"
        end
      end
    end
  end
end
