# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flexroster < Formula
  desc "A cli tool to manage your FlexRoster instance"
  homepage "https://github.com/biohackerellie/FlexRoster"
  version "1.10.6"

  on_macos do
    on_intel do
      url "https://github.com/biohackerellie/FlexRoster/releases/download/v1.10.6/FlexRoster_1.10.6_darwin_amd64.tar.gz"
      sha256 "62e11dcac4e6a109eb74d2d7e878785297974edc556b97b9eb08493946b05191"

      def install
        bin.install "flexroster"
        etc.install "config.yaml"
      end
    end
    on_arm do
      url "https://github.com/biohackerellie/FlexRoster/releases/download/v1.10.6/FlexRoster_1.10.6_darwin_arm64.tar.gz"
      sha256 "f038163933701206b3d2d983653d3f6bfec06d4e2189e997667e5f4375c37e1d"

      def install
        bin.install "flexroster"
        etc.install "config.yaml"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/biohackerellie/FlexRoster/releases/download/v1.10.6/FlexRoster_1.10.6_linux_amd64.tar.gz"
        sha256 "e439841d63105bbc15bdc4ffd801033872337ab7e7c705999c96e71ee57b4377"

        def install
          bin.install "flexroster"
          etc.install "config.yaml"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/biohackerellie/FlexRoster/releases/download/v1.10.6/FlexRoster_1.10.6_linux_arm64.tar.gz"
        sha256 "25dc89564819093920bce9447a649fa890c081a6cc2110fb4129d0ea2a96d1d8"

        def install
          bin.install "flexroster"
          etc.install "config.yaml"
        end
      end
    end
  end

  test do
    system "#{bin}/flexroster version"
  end
end
